/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zts_xtp_quote_api_QuoteApi */

#ifndef _Included_com_zts_xtp_quote_api_QuoteApi
#define _Included_com_zts_xtp_quote_api_QuoteApi
#ifdef __cplusplus
extern "C" {
#endif

/*
* Class:     com_zts_xtp_quote_api_TradeApi
* Method:    initGlog
* Signature: (Ljava/lang/String;Ljava/lang/String;)V
*/
JNIEXPORT void JNICALL Java_com_zts_xtp_quote_api_QuoteApi_initGlog
        (JNIEnv *, jobject, jstring,jstring);
/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    quoteInit
 * Signature: (SLjava/lang/String;Lcom/zts/xtp/common/enums/XtpLogLevel;)V
 */
JNIEXPORT void JNICALL Java_com_zts_xtp_quote_api_QuoteApi_quoteInit
  (JNIEnv *, jobject, jshort, jstring, jobject);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zts_xtp_quote_api_QuoteApi_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    login
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_login
  (JNIEnv *, jobject, jstring, jint, jstring, jstring, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    logout
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_logout
  (JNIEnv *, jobject);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    setHeartBeatInterval
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_zts_xtp_quote_api_QuoteApi_setHeartBeatInterval
  (JNIEnv *, jobject, jint);

/*
* Class:     com_zts_xtp_quote_api_QuoteApi
* Method:    setUDPBufferSize
* Signature: (I)V
*/
JNIEXPORT void JNICALL Java_com_zts_xtp_quote_api_QuoteApi_setUDPBufferSize
(JNIEnv *, jobject, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    subscribeMarketData
 * Signature: ([Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_subscribeMarketData
  (JNIEnv *, jobject, jobjectArray, jint, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    unSubscribeMarketData
 * Signature: ([Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_unSubscribeMarketData
  (JNIEnv *, jobject, jobjectArray, jint, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    subscribeOrderBook
 * Signature: ([Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_subscribeOrderBook
  (JNIEnv *, jobject, jobjectArray, jint, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    unSubscribeOrderBook
 * Signature: ([Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_unSubscribeOrderBook
  (JNIEnv *, jobject, jobjectArray, jint, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    subscribeTickByTick
 * Signature: ([Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_subscribeTickByTick
  (JNIEnv *, jobject, jobjectArray, jint, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    unSubscribeTickByTick
 * Signature: ([Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_unSubscribeTickByTick
  (JNIEnv *, jobject, jobjectArray, jint, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    subscribeAllMarketData
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_subscribeAllMarketData
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    unSubscribeAllMarketData
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_unSubscribeAllMarketData
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    subscribeAllOrderBook
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_subscribeAllOrderBook
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    unSubscribeAllOrderBook
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_unSubscribeAllOrderBook
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    subscribeAllTickByTick
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_subscribeAllTickByTick
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    unSubscribeAllTickByTick
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_unSubscribeAllTickByTick
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    queryAllTickers
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_queryAllTickers
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    queryTickersPriceInfo
 * Signature: ([Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_queryTickersPriceInfo
  (JNIEnv *, jobject, jobjectArray, jint, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    subscribeAllOptionMarketData
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_subscribeAllOptionMarketData
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    unSubscribeAllOptionMarketData
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_unSubscribeAllOptionMarketData
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    subscribeAllOptionOrderBook
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_subscribeAllOptionOrderBook
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    unSubscribeAllOptionOrderBook
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_unSubscribeAllOptionOrderBook
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    subscribeAllOptionTickByTick
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_subscribeAllOptionTickByTick
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zts_xtp_quote_api_QuoteApi
 * Method:    unSubscribeAllOptionTickByTick
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_quote_api_QuoteApi_unSubscribeAllOptionTickByTick
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
