/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zts_xtp_trade_api_TradeApi */

#ifndef _Included_com_zts_xtp_trade_api_TradeApi
#define _Included_com_zts_xtp_trade_api_TradeApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    getApiLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zts_xtp_trade_api_TradeApi_getApiLastError
  (JNIEnv *, jobject);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    initGlog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zts_xtp_trade_api_TradeApi_initGlog
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    tradeInit
 * Signature: (SLjava/lang/String;Ljava/lang/String;Lcom/zts/xtp/common/enums/XtpLogLevel;Lcom/zts/xtp/common/enums/XtpTeResumeType;)V
 */
JNIEXPORT void JNICALL Java_com_zts_xtp_trade_api_TradeApi_tradeInit
  (JNIEnv *, jobject, jshort, jstring, jstring, jobject, jobject);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    subscribePublicTopic
 * Signature: (Lcom/zts/xtp/common/enums/XtpTeResumeType;)V
 */
JNIEXPORT void JNICALL Java_com_zts_xtp_trade_api_TradeApi_subscribePublicTopic
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    setHeartBeatInterval
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_zts_xtp_trade_api_TradeApi_setHeartBeatInterval
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zts_xtp_trade_api_TradeApi_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    login
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Lcom/zts/xtp/common/enums/TransferProtocol;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zts_xtp_trade_api_TradeApi_login
  (JNIEnv *, jobject, jstring, jint, jstring, jstring, jobject, jstring);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    logout
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_logout
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    insertOrder
 * Signature: (IIIIIDDJIIIIJJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zts_xtp_trade_api_TradeApi_insertOrder
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jdouble, jdouble, jlong, jint, jint, jint, jint, jlong, jlong, jlong);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    cancelOrder
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zts_xtp_trade_api_TradeApi_cancelOrder
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryOrderByXtpId
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryOrderByXtpId
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryOrders
 * Signature: (Lcom/zts/xtp/trade/model/request/OrderQueryRequest;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryOrders
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryOrdersByPage
 * Signature: (Lcom/zts/xtp/trade/model/request/OrderQueryByPageReq;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryOrdersByPage
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryTradesByXtpId
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryTradesByXtpId
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryTrades
 * Signature: (Lcom/zts/xtp/trade/model/request/TraderQueryRequest;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryTrades
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryTradesByPage
 * Signature: (Lcom/zts/xtp/trade/model/request/TradeQueryByPageReq;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryTradesByPage
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryPosition
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryPosition
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryAsset
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryAsset
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryStructuredFund
 * Signature: (Lcom/zts/xtp/trade/model/request/StructuredFundInfoQueryRequest;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryStructuredFund
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    fundTransfer
 * Signature: (Lcom/zts/xtp/trade/model/request/FundTransferRequest;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zts_xtp_trade_api_TradeApi_fundTransfer
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryFundTransfer
 * Signature: (Lcom/zts/xtp/trade/model/request/FundTransferLogQueryRequest;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryFundTransfer
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryOtherServerFund
 * Signature: (Lcom/zts/xtp/trade/model/request/XTPFundQueryReq;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryOtherServerFund
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryETF
 * Signature: (Lcom/zts/xtp/trade/model/request/ETFBaseQueryRequest;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryETF
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryETFTickerBasket
 * Signature: (Lcom/zts/xtp/trade/model/request/ETFComponentQueryRequest;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryETFTickerBasket
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryIPOInfoList
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryIPOInfoList
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryIPOQuotaInfo
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryIPOQuotaInfo
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryOptionAuctionInfo
 * Signature: (Lcom/zts/xtp/trade/model/request/OptionAuctionInfoRequest;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryOptionAuctionInfo
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    getTradingDay
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zts_xtp_trade_api_TradeApi_getTradingDay
  (JNIEnv *, jobject);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    getApiVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zts_xtp_trade_api_TradeApi_getApiVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    getClientIDByXTPID
 * Signature: (Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_com_zts_xtp_trade_api_TradeApi_getClientIDByXTPID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    getAccountByXTPID
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zts_xtp_trade_api_TradeApi_getAccountByXTPID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    isServerRestart
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zts_xtp_trade_api_TradeApi_isServerRestart
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    loginALGO
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Lcom/zts/xtp/common/enums/TransferProtocol;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_loginALGO
  (JNIEnv *, jobject, jstring, jint, jstring, jstring, jobject, jstring);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryStrategy
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryStrategy
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    algoUserEstablishChannel
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_algoUserEstablishChannel
  (JNIEnv *, jobject, jstring, jint, jstring, jstring, jstring);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    insertAlgoOrder
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_insertAlgoOrder
  (JNIEnv *, jobject, jint, jstring, jstring, jstring);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    cancelAlgoOrder
 * Signature: (ZLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_cancelAlgoOrder
  (JNIEnv *, jobject, jboolean, jstring, jstring);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    getAlgorithmIDByOrder
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zts_xtp_trade_api_TradeApi_getAlgorithmIDByOrder
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    modifyUserTerminalInfo
 * Signature: (Lcom/zts/xtp/trade/model/request/XTPUserTerminalInfoReq;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_modifyUserTerminalInfo
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    creditCashRepay
 * Signature: (DLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zts_xtp_trade_api_TradeApi_creditCashRepay
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    creditCashRepayDebtInterestFee
 * Signature: (Ljava/lang/String;DLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zts_xtp_trade_api_TradeApi_creditCashRepayDebtInterestFee
  (JNIEnv *, jobject, jstring, jdouble, jstring);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    creditSellStockRepayDebtInterestFee
 * Signature: (Lcom/zts/xtp/trade/model/request/OrderInsertRequest;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zts_xtp_trade_api_TradeApi_creditSellStockRepayDebtInterestFee
  (JNIEnv *, jobject, jobject, jstring, jstring);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryCreditCashRepayInfo
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryCreditCashRepayInfo
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryCreditFundInfo
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryCreditFundInfo
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryCreditDebtInfo
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryCreditDebtInfo
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryCreditTickerDebtInfo
 * Signature: (Lcom/zts/xtp/trade/model/request/XTPClientQueryCrdDebtStockReq;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryCreditTickerDebtInfo
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryCreditAssetDebtInfo
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryCreditAssetDebtInfo
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryCreditTickerAssignInfo
 * Signature: (Lcom/zts/xtp/trade/model/request/XTPClientQueryCrdPositionStockReq;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryCreditTickerAssignInfo
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryCreditExcessStock
 * Signature: (Lcom/zts/xtp/trade/model/request/XTPClientQueryCrdSurplusStkReqInfo;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryCreditExcessStock
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryMulCreditExcessStock
 * Signature: (Lcom/zts/xtp/trade/model/request/XTPClientQueryCrdSurplusStkReqInfo;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryMulCreditExcessStock
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    creditExtendDebtDate
 * Signature: (Lcom/zts/xtp/trade/model/request/XTPCreditDebtExtendReq;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zts_xtp_trade_api_TradeApi_creditExtendDebtDate
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryCreditExtendDebtDateOrders
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryCreditExtendDebtDateOrders
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryCreditFundExtraInfo
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryCreditFundExtraInfo
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_zts_xtp_trade_api_TradeApi
 * Method:    queryCreditPositionExtraInfo
 * Signature: (Lcom/zts/xtp/trade/model/request/XTPClientQueryCrdPositionStockReq;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_zts_xtp_trade_api_TradeApi_queryCreditPositionExtraInfo
  (JNIEnv *, jobject, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
